### ISSUE TITLE
Task: day/night regime

### ISSUE THREAD

**Issue by xtrojak** [SmartBioTech/DeviceControl#37]
A periodic event to simulate day/night regime in PBR.

@JanCervenyy please answer the following questions:

1. **What lights should (red/blue/...) be used? Is this device specific task?**
   -> consider possibility to parametrise the task by particular command which should be executed
2. **Provide examples of possible regimes to have idea what we need to support.**
   -> is it just repetition of a pattern or something more complex?

**Comment by JanCervenyy** [comment]
ad 1. periodic events should be supported for any _settable_ property of each device so in general, it's not device-specific.
ad 2. we may need to set periodic alteration of lights (light / dark regime) and also temperature to simulate natural conditions. This involves also differences in red and blue light timing (different ratio of these wavelengths during mornings and evening as opposed to afternoons) a time-shifted changing of temperature when the temperature follows light decrease or increase with some lag.

Overall such periodic behavior is not events-like, but rather function-like, i.e. following a function in time (gradual changes in sunlight intensity over day timecourse).
