### ISSUE TITLE
Task: desync measure all

### ISSUE THREAD

**Issue by xtrojak** [SmartBioTech/DeviceControl#38]
Task for measuring a quantity in specified time intervals.

@JanCervenyy please answer the following questions:

1. Do we want this device-specific or general?
2. Please provide specification for individual quantities how often they should be measured.

The idea is to provide a dictionary `'time_interval: [list of commands]` specifying how often should these commands be executed (very generalised version). In addition, type/class of device might also be specified, making the task event more general.

**Comment by JanCervenyy** [comment]
ad 1. `measure_all` should be device-specific and defined by us for each individual device. Users can create their own custom `my_measure_all` via _tasks_
ad 2. this is also largely individual, but we should set some default time intervals for `measure_all`. Let's start with a default 2 min interval for all measurable parameters and I will curate the task for each device
